"""Smoke tests for the GridLab Ebook Engine CLI.

Uses only the Python stdlib (HTML intake) so the tests do not depend on the
optional markdown/pyyaml dependencies. The PDF test is skipped when weasyprint
is not installed.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent.parent
APP_ROOT = REPO_ROOT / "apps" / "ebook-engine"


CONFIG_HTML = """\
[book]
title = "Smoke Test Book"
subtitle = "A minimal test book"
author = "Test Author"
description = "Generated by test_build.py."
keywords = ["test", "smoke"]

[brand]
accent = "#2563eb"
font = '"Space Mono", ui-monospace, Menlo, monospace'
footer = "GridLab Test"

[output]
directory = "dist"
pdf = false
html = true

[analytics]
vercel = false
google = ""
matomo_url = ""
matomo_site_id = ""
"""


CONFIG_PDF = """\
[book]
title = "Smoke Test Book"
subtitle = "A minimal test book"
author = "Test Author"
description = "Generated by test_build.py."
keywords = ["test", "smoke"]

[brand]
accent = "#2563eb"
font = '"Space Mono", ui-monospace, Menlo, monospace'
footer = "GridLab Test"

[output]
directory = "dist"
pdf = true
html = false

[analytics]
vercel = false
google = ""
matomo_url = ""
matomo_site_id = ""
"""


def _weasyprint_available() -> bool:
    """Return True if weasyprint is installed and on PATH."""
    return shutil.which("weasyprint") is not None


class TestBuildSmoke(unittest.TestCase):
    """Build a minimal HTML-intake book and assert output exists."""

    def test_build_html_smoke(self) -> None:
        with tempfile.TemporaryDirectory() as tmp:
            book = Path(tmp) / "book"
            book.mkdir()

            (book / "ebook.toml").write_text(CONFIG_HTML, encoding="utf-8")
            # The HTML intake collector ignores files under 1KB, so pad the body.
            body = "<h1>Hello World</h1>\n" + "\n".join(
                f"<p>This is paragraph {i} of the smoke test.</p>"
                for i in range(1, 50)
            )
            (book / "chapter.html").write_text(body, encoding="utf-8")

            env = {"PYTHONPATH": f"{APP_ROOT}:{REPO_ROOT}/content/journal/docs"}
            result = subprocess.run(
                [sys.executable, "-m", "ebook_engine.cli", "build", str(book)],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertEqual(
                result.returncode,
                0,
                f"Build failed with stderr:\n{result.stderr}\nstdout:\n{result.stdout}",
            )

            output = book / "dist" / "index.html"
            self.assertTrue(output.exists(), f"Expected output file not found: {output}")
            self.assertGreater(
                output.stat().st_size,
                0,
                f"Output file is empty: {output}",
            )

            html = output.read_text(encoding="utf-8")
            self.assertIn("Hello World", html)
            self.assertIn("smoke test", html)

    @unittest.skipUnless(
        _weasyprint_available(),
        "weasyprint not installed; install with 'brew install weasyprint' or 'apt install weasyprint'",
    )
    def test_build_pdf_smoke(self) -> None:
        """Build a minimal HTML-intake book to PDF and assert output exists."""
        with tempfile.TemporaryDirectory() as tmp:
            book = Path(tmp) / "book"
            book.mkdir()

            (book / "ebook.toml").write_text(CONFIG_PDF, encoding="utf-8")
            # The HTML intake collector ignores files under 1KB, so pad the body.
            body = "<h1>Hello World</h1>\n" + "\n".join(
                f"<p>This is paragraph {i} of the smoke test.</p>"
                for i in range(1, 50)
            )
            (book / "chapter.html").write_text(body, encoding="utf-8")

            env = {"PYTHONPATH": f"{APP_ROOT}:{REPO_ROOT}/content/journal/docs"}
            result = subprocess.run(
                [sys.executable, "-m", "ebook_engine.cli", "build", str(book)],
                cwd=REPO_ROOT,
                capture_output=True,
                text=True,
                env=env,
            )

            self.assertEqual(
                result.returncode,
                0,
                f"Build failed with stderr:\n{result.stderr}\nstdout:\n{result.stdout}",
            )

            output = book / "dist" / "smoke-test-book.pdf"
            self.assertTrue(output.exists(), f"Expected PDF file not found: {output}")
            self.assertGreater(
                output.stat().st_size,
                0,
                f"PDF file is empty: {output}",
            )


if __name__ == "__main__":
    unittest.main()
